import { db } from '@/lib/db';
import { recordAudit } from '@/lib/audit';
import type { CommissionEntityType, CommissionRule, Prisma } from '@prisma/client';
import type { SessionUser } from '@/lib/auth';

export interface CommissionShare {
  entityType: CommissionEntityType;
  amountMinor: number;
  commissionRuleId: string | null;
  representativeId: string | null;
}

export interface CommissionSplit {
  totalMinor: number;
  shares: CommissionShare[];
}

function applyRule(rule: CommissionRule, totalMinor: number): number {
  if (rule.flatAmountMinor !== null && rule.flatAmountMinor !== undefined) {
    return Math.min(rule.flatAmountMinor, totalMinor);
  }
  if (rule.percentage !== null && rule.percentage !== undefined) {
    return Math.round((totalMinor * rule.percentage) / 100);
  }
  return 0;
}

/**
 * Resolves the active rule for one entity type: a tenant-specific rule beats a global
 * (tenantId null) one, so the platform can set a default and still negotiate per clinic.
 */
async function resolveRule(entityType: CommissionEntityType, tenantId: string): Promise<CommissionRule | null> {
  const rules = await db.commissionRule.findMany({
    where: { entityType, isActive: true, OR: [{ tenantId }, { tenantId: null }] },
  });
  return rules.find((r) => r.tenantId === tenantId) ?? rules.find((r) => r.tenantId === null) ?? null;
}

/**
 * Computes how one booking's money is divided. Nothing here is hard-coded — the brief's
 * worked example (20 JOD booking → platform 10%, representative 3%, clinic the rest) is
 * just what this produces when those rules/plan are configured, and changing the numbers
 * is a data change, not a code change.
 *
 * Two deliberate design points:
 *  - The platform's cut comes from the tenant's ACTIVE subscription plan
 *    (`SubscriptionPlan.bookingCommissionPct`), which is what makes the SaaS model
 *    coherent: the Free plan takes a booking commission, Pro/Enterprise take 0% and
 *    monetise through the subscription fee instead. A PLATFORM CommissionRule is the
 *    fallback when a tenant has no active subscription at all.
 *  - The clinic receives the exact remainder rather than its own percentage, so the split
 *    always sums to the total to the fils and rounding can never mint or destroy money.
 */
export async function computeCommissionSplit(appointmentId: string): Promise<CommissionSplit | null> {
  const appointment = await db.appointment.findUnique({ where: { id: appointmentId } });
  if (!appointment) return null;

  const totalMinor = appointment.priceMinor;
  const tenantId = appointment.tenantId;
  const shares: CommissionShare[] = [];

  // --- Platform ---
  const subscription = await db.subscription.findFirst({
    where: { tenantId, status: 'ACTIVE' },
    include: { plan: true },
    orderBy: { createdAt: 'desc' },
  });

  if (subscription) {
    const pct = subscription.plan.bookingCommissionPct;
    if (pct > 0) {
      shares.push({
        entityType: 'PLATFORM',
        amountMinor: Math.round((totalMinor * pct) / 100),
        commissionRuleId: null,
        representativeId: null,
      });
    }
  } else {
    const platformRule = await resolveRule('PLATFORM', tenantId);
    if (platformRule) {
      const amount = applyRule(platformRule, totalMinor);
      if (amount > 0) {
        shares.push({ entityType: 'PLATFORM', amountMinor: amount, commissionRuleId: platformRule.id, representativeId: null });
      }
    }
  }

  // --- Representative (only when the booking was generated by one) ---
  if (appointment.bookedByRepresentativeId) {
    const repRule = await resolveRule('REPRESENTATIVE', tenantId);
    if (repRule) {
      const amount = applyRule(repRule, totalMinor);
      if (amount > 0) {
        shares.push({
          entityType: 'REPRESENTATIVE',
          amountMinor: amount,
          commissionRuleId: repRule.id,
          representativeId: appointment.bookedByRepresentativeId,
        });
      }
    }
  }

  // --- Doctor (optional; only if the tenant configured a doctor split) ---
  const doctorRule = await resolveRule('DOCTOR', tenantId);
  if (doctorRule) {
    const amount = applyRule(doctorRule, totalMinor);
    if (amount > 0) {
      shares.push({ entityType: 'DOCTOR', amountMinor: amount, commissionRuleId: doctorRule.id, representativeId: null });
    }
  }

  // --- Clinic: exact remainder ---
  const allocated = shares.reduce((sum, s) => sum + s.amountMinor, 0);
  const remainder = totalMinor - allocated;
  if (remainder < 0) {
    throw new CommissionOverAllocationError(
      `Configured commission rules allocate ${allocated} of a ${totalMinor} booking, exceeding the total.`
    );
  }
  shares.push({ entityType: 'CLINIC', amountMinor: remainder, commissionRuleId: null, representativeId: null });

  return { totalMinor, shares };
}

export class CommissionOverAllocationError extends Error {}

/**
 * Persists an already-computed split. Split computation is deliberately separated from
 * persistence so the caller can validate the configuration *before* taking any money —
 * see collectAppointmentPayment. Idempotent per appointment.
 */
export async function persistCommissions(appointmentId: string, split: CommissionSplit, actor: SessionUser) {
  const existing = await db.commission.count({ where: { appointmentId, status: { not: 'CANCELLED' } } });
  if (existing > 0) return [];

  const appointment = await db.appointment.findUnique({ where: { id: appointmentId } });
  if (!appointment) return [];

  const created = await db.$transaction(
    split.shares.map((share) =>
      db.commission.create({
        data: {
          appointmentId,
          tenantId: appointment.tenantId,
          entityType: share.entityType,
          amountMinor: share.amountMinor,
          currency: appointment.currency,
          commissionRuleId: share.commissionRuleId,
          representativeId: share.representativeId,
          status: 'PENDING',
        },
      })
    )
  );

  await recordAudit({
    actorUserId: actor.id,
    tenantId: appointment.tenantId,
    action: 'COMMISSIONS_GENERATED',
    entityType: 'Appointment',
    entityId: appointmentId,
    afterState: {
      totalMinor: split.totalMinor,
      shares: split.shares.map((s) => ({ entityType: s.entityType, amountMinor: s.amountMinor })),
    },
  });

  return created;
}

/** A refunded booking must not leave payable commissions behind. */
export async function cancelCommissionsForAppointment(appointmentId: string, actor: SessionUser) {
  const { count } = await db.commission.updateMany({
    where: { appointmentId, status: 'PENDING' },
    data: { status: 'CANCELLED' },
  });

  if (count > 0) {
    const appointment = await db.appointment.findUnique({ where: { id: appointmentId } });
    await recordAudit({
      actorUserId: actor.id,
      tenantId: appointment?.tenantId ?? null,
      action: 'COMMISSIONS_CANCELLED',
      entityType: 'Appointment',
      entityId: appointmentId,
      afterState: { cancelledCount: count },
    });
  }

  return count;
}

// ---------- Reads ----------

export async function listCommissionRules() {
  return db.commissionRule.findMany({
    include: { tenant: { select: { id: true, nameAr: true } } },
    orderBy: [{ tenantId: 'asc' }, { entityType: 'asc' }],
  });
}

export async function upsertCommissionRule(
  input: { id?: string; tenantId?: string | null; entityType: CommissionEntityType; percentage?: number | null; flatAmountMinor?: number | null; isActive?: boolean },
  actor: SessionUser
) {
  const data: Prisma.CommissionRuleUncheckedCreateInput = {
    tenantId: input.tenantId ?? null,
    entityType: input.entityType,
    percentage: input.percentage ?? null,
    flatAmountMinor: input.flatAmountMinor ?? null,
    isActive: input.isActive ?? true,
  };

  const rule = input.id
    ? await db.commissionRule.update({ where: { id: input.id }, data })
    : await db.commissionRule.create({ data });

  await recordAudit({
    actorUserId: actor.id,
    tenantId: rule.tenantId,
    action: input.id ? 'COMMISSION_RULE_UPDATED' : 'COMMISSION_RULE_CREATED',
    entityType: 'CommissionRule',
    entityId: rule.id,
    afterState: { entityType: rule.entityType, percentage: rule.percentage, flatAmountMinor: rule.flatAmountMinor },
  });

  return rule;
}

export async function listRepCommissions(representativeId: string) {
  const commissions = await db.commission.findMany({
    where: { representativeId },
    include: {
      appointment: {
        include: {
          doctor: { include: { user: { select: { name: true } } } },
          patient: { include: { user: { select: { name: true } } } },
        },
      },
    },
    orderBy: { createdAt: 'desc' },
  });

  const totals = commissions.reduce(
    (acc, c) => {
      if (c.status === 'PAID') acc.paidMinor += c.amountMinor;
      else if (c.status === 'PENDING') acc.pendingMinor += c.amountMinor;
      return acc;
    },
    { paidMinor: 0, pendingMinor: 0 }
  );

  return { commissions, ...totals };
}

export async function listTenantCommissions(tenantId: string) {
  return db.commission.findMany({
    where: { tenantId },
    include: { appointment: { select: { id: true, scheduledAt: true, priceMinor: true } } },
    orderBy: { createdAt: 'desc' },
    take: 200,
  });
}
