import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { errorResponse } from '@/lib/api/respond';

export const dynamic = 'force-dynamic';

/**
 * Serves the generated OpenAPI document.
 *
 * Reads the committed `public/openapi.json` rather than generating on request: generation
 * imports every Zod schema and walks the filesystem, which is a build-time job, not
 * something to do per request. The file is regenerated by
 * `npx tsx scripts/generate-openapi.ts`, which fails if any handler is undocumented.
 */
export async function GET() {
  try {
    const spec = await readFile(join(process.cwd(), 'public', 'openapi.json'), 'utf8');
    return new Response(spec, {
      headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'public, max-age=300' },
    });
  } catch {
    return errorResponse(
      'SPEC_NOT_GENERATED',
      'The API document has not been generated. Run: npx tsx scripts/generate-openapi.ts',
      503
    );
  }
}
